_target_: datamodules.peft_dm.PeftDataModule
samples_dir: "/home/nkcemeka/Documents/Datasets/Nottingham/excerpts/alto/samples"
abc_dir: "/home/nkcemeka/Documents/Datasets/Nottingham/excerpts/alto/abc_il"
percent_split: 0.8
aug_flag: True
