# Audio samples extraction config
SAMPLE_RATE: 24000
AUDIO_DIRS:
  - "/home/nkcemeka/Documents/Datasets/Nottingham/excerpts/alto/audio"
OUT_DIRS:
  - "/home/nkcemeka/Documents/Datasets/Nottingham/excerpts/alto/samples"
