# Audio samples extraction config
SAMPLE_RATE: 24000
AUDIO_DIRS:
  - "/home/nkcemeka/Documents/Datasets/MelodyT5/excerpts/piano/audio"
OUT_DIRS:
  - "/home/nkcemeka/Documents/Datasets/MelodyT5/excerpts/piano/samples"
